describe('Login', () => {
    it('TC01 - Login com credenciais válidas - Positivo', () => {
       cy.visit('https://www.saucedemo.com/v1/index.html')
       cy.get('input#user-name').type('standard_user')
       cy.get('input#password').type('secret_sauce')
       cy.get('input.btn_action').click()
    })
    it('TC02 - Login com usarname inválido - Negativo', () => {
        cy.visit('https://www.saucedemo.com/v1/index.html')
        cy.get('input#user-name').type('User_standard')
        cy.get('input#password').type('secret_sauce')
        cy.get('input.btn_action').click()
        cy.get('h3').should('contain.html', 'error-button')
        .and('contain.text', 'Epic sadface: ')
        .and('contain.text', 'Username and password do not match any user in this service')  
    })
    it('TC03 - Login com password inválido - Negativo', () => {
        cy.visit('https://www.saucedemo.com/v1/index.html')
        cy.get('input#user-name').type('standard_user')
        cy.get('input#password').type('Sauce_secret')
        cy.get('input.btn_action').click()
        cy.get('h3').should('contain.html', 'error-button')
        .and('contain.text', 'Epic sadface: ')
        .and('contain.text', 'Username and password do not match any user in this service') 
    })
    it('TC04 - Login com usarname vazio - Negativo', () => {
        cy.visit('https://www.saucedemo.com/v1/index.html')
        cy.get('input#password').type('secret_sauce')
        cy.get('input.btn_action').click() 
        cy.get('h3').should('contain.html', 'error-button')
        .and('contain.text', 'Epic sadface: ')
        .and('contain.text', 'Username is required')  
    })
    it('TC05 - Login com password vazio - Negativo', () => {
        cy.visit('https://www.saucedemo.com/v1/index.html')
        cy.get('input#user-name').type('standard_user')
        cy.get('input.btn_action').click() 
        cy.get('h3').should('contain.html', 'error-button')
        .and('contain.text', 'Epic sadface: ')
        .and('contain.text', 'Password is required') 
    })
})